import {create} from 'zustand';

let store = (set) => ({
    chatId: '',
    owner: '',
    is_participant: false,
    group_is_private: false,
    closeMediaPopup: false,
    participants: '',
    groupName: '',
    groupIcon: '',
    removeParticipants: false,
    openProfile: false,
    groupCreatedAt: '',
    groupParticipantsList: [],
    groupDescription: '',
    inviteLink: '',
    searchTerm: '',
    web3RandomMsg: '',
    web3ResponseToken: '',
    talkId: '',
    groupSettingOpen: false,
    isGroupDescOpen: false,
    joinGroup: false,
    

    addChatId: (chatId) => set({ chatId }),
    setTalkId: (talkId) => set({ talkId }),
    addOwner: (owner) => set({ owner }),
    IsParticipant: (is_participant) => set({ is_participant }),
    addParticipants: (participants) => set({ participants }),
    addGroupName: (groupName) => set({ groupName }),
    addGroupIcon: (groupIcon) => set({ groupIcon }),
    updateGroup: (removeParticipants) => set({ removeParticipants }),
    OpenProfile: (openProfile) => set({ openProfile }),
    GroupCreatedAt: (groupCreatedAt) => set({ groupCreatedAt }),
    GroupParticipantsList: (groupParticipantsList) => set({ groupParticipantsList }),
    GroupDescription: (groupDescription) => set({ groupDescription }),
    InviteLink: (inviteLink) => set({ inviteLink }),
    GroupIsPrivate: (group_is_private) => set({ group_is_private }),
    CloseMediaPopup: (closeMediaPopup) => set({ closeMediaPopup }),
    setSearchTerm: (searchTerm) => set({ searchTerm }),
    Web3RandomMsg: (Web3RandomMsg) => set({ Web3RandomMsg }),
    Web3ResponseToken: (Web3ResponseToken) => set({ Web3ResponseToken }),
    GroupSettingOpen: (groupSettingOpen) => set({ groupSettingOpen }),
    GroupDescOpen: (isGroupDescOpen) => set({ isGroupDescOpen }),
    ISJoinGroup: (joinGroup) => set({ joinGroup }),

    resetStore: () => {
        set({
            chatId: '',
            owner: '',
            joinGroup: false,
            is_participant: false,
            isGroupDescOpen: false,
            group_is_private: false,
            closeMediaPopup: false,
            participants: '',
            groupName: '',
            groupIcon: '',
            removeParticipants: '',
            openProfile: false,
            groupCreatedAt: '',
            groupParticipantsList: [],
            groupDescription: '',
            inviteLink: '',
            searchTerm: '',
            web3RandomMsg: '',
            web3ResponseToken: '',
            talkId: '',
            groupSettingOpen: false,
        });
      },
});

const useStore = create(store);
export default useStore;